### ISSUE TITLE
[Question] Test on local

### ISSUE THREAD

**Issue by djKooks** [katalchain/blockchain#90]
Hello, this is just a question.

Is there a way to access on running chain in local? 🙏

**Comment by retotrinkler** [comment]
Hi @djKooks did you try those commands already?
```sh
./scripts/init.sh # Initialize WASM build environment
git clone git@github.com:Trinkler/katal-chain.git
cd katal-chain/
./scripts/init.sh # Initialize WASM build environment
cargo install --locked --path . # Build and install native binaries
katal # Synchronize chain data
```

it should automatically connect you to the [running chain](https://telemetry.polkadot.io/#list/Katal)

**Comment by djKooks** [comment]
@retotrinkler thanks for reply!
I've got error from `cargo install --locked --path .`:  
```
   Compiling katal-chain v0.3.0 (/Users/kwangin.jung/workspace/etc/katal-chain)
error: couldn't read node/src/../runtime/wasm/target/wasm32-unknown-unknown/release/katal_runtime_wasm.compact.wasm: No such file or directory (os error 2)
   --> node/src/chain_spec.rs:136:10
    |
136 |             code: include_bytes!("../runtime/wasm/target/wasm32-unknown-unknown/release/katal_runtime_wasm.compact.wasm").to_vec(),
    |                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: couldn't read node/src/../runtime/wasm/target/wasm32-unknown-unknown/release/katal_runtime_wasm.compact.wasm: No such file or directory (os error 2)
  --> node/src/service.rs:29:2
   |
29 |     include_bytes!("../runtime/wasm/target/wasm32-unknown-unknown/release/katal_runtime_wasm.compact.wasm")
   |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
...
```

I'm working on MacOS.
Could you find the problem?

**Comment by retotrinkler** [comment]
Ah apologies there was a `./scripts/build.sh` missing.

```bash
cd katal-chain/
./scripts/init.sh
./scripts/build.sh
cargo install --locked --path . --force
katal
```

should work. Please lmk if not.

**Comment by djKooks** [comment]
@retotrinkler seems working fine, thanks!
On readme:
```
cargo build # Build native binaries in debug mode
./target/debug/katal purge-chain --dev # Remove the whole chain data
./target/debug/katal --dev # Run chain in dev mode
```
Is it means that `katal` command runs the chain? If it is, is there some kind of API that could access to this chain(such as making contracts...)?

**Comment by djKooks** [comment]
@retotrinkler thanks! 
Is there other way to access with other language, or script? Just curiosity...

**Comment by retotrinkler** [comment]
There are few being built eg for [rust](https://github.com/scs/substrate-api-client) would assume [c++](https://github.com/soramitsu/kagome) will also have one at some point. Any specific language you're looking for?

**Comment by djKooks** [comment]
@retotrinkler thanks! I'll check this first.

**Comment by retotrinkler** [comment]
There was indeed a problem. `katalchain --chain ./node/res/katalchain.json` should work.
Let me know if not.
Thanks
